### ISSUE TITLE
viaversion where

### ISSUE THREAD

**Issue by CDFN** [KennyTV/list-of-shame#2]
i see no viaversion on list add pls

**Comment by mikroskeem** [comment]
ur dum

**Comment by Chew** [comment]
What is viaversion

**Comment by CDFN** [comment]
plugin allowing joining server with legacy versions, as we know supporting legacy software shouldn't have place

**Comment by KennyTV** [comment]
who are you

**Comment by Draycia** [comment]
whats this

**Comment by mikroskeem** [comment]
this is heresy

**Comment by mikroskeem** [comment]
kenny smells tho

**Comment by Chew** [comment]
> plugin allowing joining server with legacy versions, as we know supporting legacy software shouldn't have place
this is wrong, I just looked into it. it allows newer clients to join older servers. great for making sure you're up to date when spigot just released and there's bugs.
via backwards definitely needs to be on here

**Comment by MrPowerGamerBR** [comment]
Very very very late response to this issue but I was looking into the list but I would argue that ViaVersion by itself is more "evil" than ViaBackwards/ProtocolSupport.

ViaVersion makes you use a outdated server software just to allow newer clients to join, so you are still running a out of date server versions (with all the security holes that it has & stuff) while ViaBackwards/ProtocolSupport allows you to run a up to date server, with all the new bells and whistles that Minecraft has, while still allowing those stubborn players that hate updating to a newer version. I don't think they should be labeled as "more evil" (well, ProtocolSupport is labeled as that) than ViaVersion by itself.

Unless if ProtocolSupport has some "evil" that I don't know about 👀, some of the topics in the list of shame really could've have more explanations attached to it so people that are not in the loop can understand why they should be shamed.

**Comment by KennyTV** [comment]
Most descriptions are intentionally kept vague/basically meaningless, so that it's less likely for people to mistake this as a definitive and serious "do-not-use" list 😎
