### ISSUE TITLE
Removal Request

### ISSUE THREAD

**Issue by Vagdedes** [KennyTV/list-of-shame#20]
Howdy there! I would like to request my plugin Spartan to be removed from this list for the following reasons:

1. I no longer use my plugin to heavily advertise, such as in the past where I had random messages pop up.
2. "A Minecraft server uses just one CPU core" This was removed a while ago, excuse my stupidity.
3. I am aware my plugin doesn't have favourable performance and I've drastically improved it as seen from my updates. It will no longer set your server on fire, but maybe will still light a few torches, UwU

Thanks to KennyTV for instructing me on what to do for a transparent request. He's a cool dude, he's also upside down, makes me want to throw up the burger I just ate. Anyway, if you read this till the end, congrats, your time was well wasted.

**Comment by KennyTV** [comment]
thenk
