### ISSUE TITLE
add spartan back

### ISSUE THREAD

**Issue by EchoRapidz** [KennyTV/list-of-shame#24]
add tps killer back because the stuff he "corrected" is literally still there

![image](https://user-images.githubusercontent.com/55660010/104299476-2e767780-54bd-11eb-938e-3a1ba36d084f.png)

**Comment by EuanM199** [comment]
YES, Add it back!

**Comment by GoldenEdit** [comment]
+1 This needs fixing, Spartan dev is a liar.

**Comment by LegendaryBob13** [comment]
+1 Bring this terrible plugin back on the LIST OF SHAME!

**Comment by Vagdedes** [comment]
This invalid sentence wasn't just on the plugin's overview page, it was also in some item description in an inventory menu. I had only removed the item description, not the one on the plugin's overview page because I didn't notice it. No problem, here you go https://prnt.sc/wlsfhf, corrected.

**Comment by EchoRapidz** [comment]
Still deserves to be on the list :P

**Comment by GoldenEdit** [comment]
> This invalid sentence wasn't just on the plugin's overview page, it was also in some item description in an inventory menu. I had only removed the item description, not the one on the plugin's overview page because I didn't notice it. No problem, here you go https://prnt.sc/wlsfhf, corrected.

Thanks for correcting it. But you need to remember that your plugin is not performant, has many bypasses, falses, and disablers. When people show you them and ask for a refund you take money out of the refund and claim that the money you took out was for 'support'. Please correct me if I'm wrong but this happened to @EchoRapidz

**Comment by EchoRapidz** [comment]
That was over a year ago i don't really care about that anymore, but spartan still deserves to be on the list

**Comment by EuanM199** [comment]
+1 should be on the list, lying then correcting it after being caught doesn't change anything, you still lied

**Comment by Vagdedes** [comment]
As EchoRapidz said, this is over a year ago. I have improved my refund policy, and it is much friendlier than in the past, so with the current system EchoRapidz would get a full refund minus a small amount for the PayPal fees.

Spartan doesn't deserve to be on this list. You made an issue which was about an invalid sentence that I had forgotten to remove from its 2nd location, and I removed it ASAP, I didn't lie. My plugin currently has zero disablers, it has received tons of performance improvements, and bypasses & false positives are corrected in a daily basis. Feel free to check my updates, every correction is listed.

If you want to judge me, feel free, but at least judge me with what I am doing now. Except the refund part, which as you can see has been corrected as well, anything else that you said about Spartan can be said about any other anticheat without sense whatsoever. My work only improves over time.

**Comment by EchoRapidz** [comment]
1. I didn't bring up the refund thing someone else did
2. An opinion cannot be wrong evan
![image](https://user-images.githubusercontent.com/55660010/104319657-14e32900-54d9-11eb-9802-f0100f6beeef.png)
