### ISSUE TITLE
New list of shame people

### ISSUE THREAD

**Issue by Anarchist-byte** [KennyTV/list-of-shame#26]
New list: https://ibb.co/tMLwv8W
![Снимок экрана 2021-01-12 220031](https://user-images.githubusercontent.com/70373707/104360107-9c548a80-5521-11eb-8b97-b44dfb465d19.png)

**Comment by Andre601** [comment]
Okay? And?

**Comment by Anarchist-byte** [comment]
Just nothing)
Can u pls say why FAWE is bad thing?

**Comment by Andre601** [comment]
Lot's of bugs I would say.

**Comment by Anarchist-byte** [comment]
Well, if u  used it a few months later, u would find more bugs)
FAWE on official page of project saying that this is just a beta.

**Comment by EchoRapidz** [comment]
FAWE is known for causing world corruption and other stuff
