### ISSUE TITLE
Add iridescent

### ISSUE THREAD

**Issue by Ehhthan** [kennytv/list-of-shame#37]
If you want a plugin that will convert all of your chat components into text and completely mess them up, [Iridescent ](https://www.spigotmc.org/resources/%E2%9C%8F%EF%B8%8F-iridescent-%E2%9C%8F%EF%B8%8F-1-16-x-add-new-hex-colors-to-your-server-supports-gradients.81322/)is for you!

**Comment by kacperleague9** [comment]
could you elaborate?
