### ISSUE TITLE
Removal request

### ISSUE THREAD

**Issue by Jakubk15** [KennyTV/list-of-shame#42]
I suggest removing Kangarko from this list, because in my opinion his Java + Bukkit course isn't really bad. JetBrains Academy is more expensive, because it's 49 € monthly, and 249 € only yearly, and it's Java only. Kangarko's course is 97 € lifetime (Java + Bukkit), which for me it's a good deal and I don't think he should be on this list. He put lot of effort into his courses and is updating them. This is only my suggestion.

**Comment by CodeByCam** [comment]
🤐

**Comment by JRoy** [comment]
You have a fair point, but this doesn't change the fact that in Australia there are 48 million Kangaroos and in Philadelphia there are 1.57 million people. So if the Kangaroos decide to invade Philadelphia, each person will have to fight approximately 31 kangaroos.

**Comment by Jakubk15** [comment]
Ok.

**Comment by Jakubk15** [comment]
Ok, we can close this issue.

**Comment by E404NNF** [comment]
noooooooo
