### ISSUE TITLE
Urgent

### ISSUE THREAD

**Issue by 360matt** [KennyTV/list-of-shame#49]
Delete this page because j'ai une grosse bite

**Comment by 360matt** [comment]
And then, Huuuuuumm CHaaraaaalll. La viande de qualité, mangez moins de viande, mais mangez-en mieux.

**Comment by Proximyst** [comment]
you're a perfect candidate for the list of shame

**Comment by 360matt** [comment]
I suggère, for a better quality of ze shame list, sponsoring the magazin: Intermarché - Tous unis contre la vie chère.

**Comment by 360matt** [comment]
Vive Marine le pen.
Vive Zemmour.

Vive la droite.
Vive la France.

Concevons notre culture, nos frontières, nos villages, notre langue.

Supprimons les milliards de fraude de la CAF.
Jugeons les délinquants, multirécidivistes de 7 interpellations.

Nique la république,
Vive la France.

**Comment by KennyTV** [comment]
I sure hope the right party doesn't live too long - take your political mis-views somewhere else.
