### ISSUE TITLE
DMCA Report

### ISSUE THREAD

**Issue by 360matt** [KennyTV/list-of-shame#50]
Yo c'est Squeeziiiiiiiiieeeee !!!

Bon déjà, mes opisions politiques sont pas erronées puisque 1/2 électeurs votent pour Marine le Pen (voir élections 2017).
En 2022 elle passera, et elle baisera tout le monde avec son gode-ceinture.

Azy, t'as l'seum que la France soit le premier pays militaire européen.
Moi j'adore les Dassault Rafales :) 
Ils font ``vrooaaaannnngg`` et ``brrrruuuuunnnmmm``, mais ça on aura l'occassion d'y revenir.

Hey marcel ?? (@Shawiizz), regarde comment on baise des allemands.
[https://www.youtube.com/watch?v=3LrPAz4cjh0](url)
Bon, on avais des camouflages de merde, mais même avec ça on a gagné la guerre.

Bref, c'est pas que je m'ennuie moi, mais j'vais regarder un ptit risitas. ISSOU.

**Comment by KennyTV** [comment]
This is not the place for your tantrums.

**Comment by 360matt** [comment]
D'accord mec, mais par contre excuse-toi pour les millions de français tué durant la seconde guerre mondiale.
