### ISSUE TITLE
Some thoughts 

### ISSUE THREAD

**Issue by James-P-Bennett** [kennytv/list-of-shame#58]
Great list, but I would argue that Viaversion is necessary for running a production server between updates. It buys administrators time to update whilst keeping wipe schedules consistent and not choke out the playerbase on new versions. I was surprised to find it in the list considering it's a drag-and-drop plugin that has no issues or server performance whatsoever. I also feel the focus of shame should be more towards server admins that allow protocol support for severely outdated clients (such as 1.7.10)
Think of Viaversion as more of a great tool when utilized properly.
Other than that, this list is pretty much spot-on. 

Bad plugin devs like Songoda, Kangarko and a few other unmentionables should also be shown the spotlight of shame a little brighter. Songoda and his small army will attempt to manipulate and spin webs of lies to cover up past and present transgressions and their plugins frequently break and cause permanent performance issues that _require a full server wipe in order to fix._ Songoda was eventually banned from Spigot which resulted in the new shady web marketplace. Don't use plugins made by or associated with Songoda if you value privacy.

**Comment by Andre601** [comment]
ViaVersion is on the list because it allows server owners to keep their server on 1.8 while allowing newer versions to join it.
Or in other words: It allows a stone age version of Minecraft to still be used to this day.

**Comment by kennytv** [comment]
It's a bit of a joke anyways. A keen eye might have noticed that I am one of the current Via maintainers. :p

**Comment by Hazmadd** [comment]
> It's a bit of a joke anyways. A keen eye might have noticed that I am one of the current Via maintainers. :p

You had me in the first half, not gonna lie

**Comment by Andre601** [comment]
Also, the fact people like you use it on newer versions doesn't destroy the fact that ViaVersion is mostly used to allow newer clients on old servers, namely 1.8

**Comment by Hazmadd** [comment]
> Also, the fact people like you use it on newer versions doesn't destroy the fact that ViaVersion is mostly used to allow newer clients on old servers, namely 1.8

By that logic we should add spigot as a whole to the list. There are many of the worst types of servers imaginable out there, all running spigot.

**Comment by Hazmadd** [comment]
Once more, misuse of the tool should not be blamed on the tool itself.

**Comment by kacperleague9** [comment]
@Hazmadd kenny works in viaversion lol
